Подправил парсинг с добавлением в БД и выводом в браузер
EliSoftCom/Final_project pull request #17
Opened 2024-07-17 17:21 UTC by Cosmmoss

2024-07-19 09:25 UTC, lwof requested changes
Основное что вызывает вопросы это user_required. В коментариях подробнее описал, почему мне кажется что с ним надо сделать что-то. 
И пара мелких замечаний вроде убрать принты. 
В целом - хорошее направление работы.

2024-07-19 09:25 UTC, lwof commented on requirements.txt
> +email_validator==2.2.0
Хочу что бы твоя версия  requirements оказался в мэйн.

2024-07-19 09:25 UTC, lwof commented on webapp/__init__.py
> +            user = User.query.filter(User.username == form.username.data).first()
one тут должно быть вместо first.
и по хорошему обработать исключения которые алхимия может кидать.

2024-07-19 09:25 UTC, lwof commented on webapp/__init__.py
> +    @app.route('/get_data_site')
подозреваю что это тоже должно быть за логином с  @login_required

2024-07-19 09:25 UTC, lwof commented on webapp/decorators.py
> +def user_required(func):
Хм, а чем тебе @login_required  не подошел? ИМХО этот декоратор нормально так добавляет сложности проекту, и используется всего один раз. 

* Или добавить докстринг с причинами такого решения, и объяснить чем этот декоратор выгодно отличается от @login_required
* Либо отрефакторить на использование  @login_required

2024-07-19 09:25 UTC, lwof commented on webapp/models.py
> +        print(self.role)
Убери принт плиз.

2024-07-19 09:25 UTC, lwof commented on webapp/models.py
> +    role: Mapped[str] = mapped_column(String(10), index=True)
не думаю что тебе нужен индекс по роли.

2024-07-19 15:44 UTC, Cosmmoss commented on webapp/__init__.py
> +            user = User.query.filter(User.username == form.username.data).first()
Если меняю на one, выдаёт ошибку в случае неправильного пароля или логина: sqlalchemy.exc.NoResultFound: No row was found when one was required

2024-07-21 14:54 UTC, lwof approved these changes
👌

2024-07-21 15:59 UTC, merged