Fixed scheduled parsing and file init.py
EliSoftCom/Final_project pull request #22
Opened 2024-07-25 20:16 UTC by Cosmmoss

Внёс изменения в файлы приложения, особенно - init.py. После этого заработал парсинг по расписанию.

2024-07-25 20:27 UTC, lwof requested changes
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on create_admin.py
> +# from getpass import getpass
Ты почто весь файл закомментировал?

2024-07-25 20:27 UTC, lwof commented on create_admin.py
> +# with create_app.app_context():
тут верни обратно на app

2024-07-25 20:27 UTC, lwof commented on parser_main.py
> +@create_app.shell_context_processor
нет, тут должен быть app. Так нельзя рефакторить. 
Лучше удали весь файл. (Он кажется и так не работал)
Если что из истории достанем.

2024-07-25 20:27 UTC, lwof commented on tasks.py
> +flask_app = create_app()
Назови переменную просто  app, что бы дальше не переименовывать.

2024-07-25 20:27 UTC, lwof commented on webapp/__init__.py
> +
Закоментированный код - удали.

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +# from webapp import login
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +    # querys: so.WriteOnlyMapped['Query'] = so.relationship(back_populates='author')
Не надо так. 
Зачем удаляешь?

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +    # @property
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +# class Query(db.Model):
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +    # @login.user_loader
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on webapp/models.py
> +#     def __repr__(self):
Не коментируй код.

2024-07-25 20:27 UTC, lwof commented on webapp/routes.py
> +# from flask import render_template, flash, redirect, url_for, request
Не коментируй код.

2024-07-25 20:29 UTC, lwof requested changes
Плохо что в одном ПР смешаны не связанные друг с другом изменения - рефакторинг на использование create_app, и настройка celery. Лучше делать по отдельности.

2024-07-26 06:23 UTC, Cosmmoss commented on tasks.py
> +flask_app = create_app()
Здесь не понял - где дальше не переименовывать?

2024-07-26 06:50 UTC, Cosmmoss commented on tasks.py
> +flask_app = create_app()
Если переменную назвать арр, то селери её отрабатывает и ошибка появляется та же.

2024-07-26 11:59 UTC, lwof approved these changes
В целом, можно мерджить.

2024-07-26 11:59 UTC, lwof commented on tasks.py
> +flask_app = create_app()
А, понял. Ну можно указывать имя селери явно. Но и так тоже годится.

2024-07-26 11:59 UTC, lwof commented on webapp/__init__.py
> +    app.config.from_pyfile('config.py')
в readme указан Class-based config. Кажется что from_pyfile его не поймет. 
Я бы вернул тут к from_object, а твой локальный конфиг переделать в класс.

2024-07-26 14:28 UTC, merged