Created parser Drom
EliSoftCom/Final_project pull request #8
Opened 2024-06-22 14:33 UTC by Cosmmoss

2024-06-22 16:16 UTC, lwof requested changes

2024-06-22 16:16 UTC, lwof commented on get_data.py
> +        all_data = soup.find('div', class_='css-1nvf6xk eojktn00').find('div').findAll('a')
Хм, думаешь это имя класса будет постоянным? У меня есть сомнения, что можно на него полагаться.

2024-06-22 16:16 UTC, lwof commented on get_data.py
> +def get_data():
сделай что бы эта функция принимала html как аргумент
и нужно более подходящее имя придумать.  get_data  не отображает что и откуда мы берем. 
И файл тоже стоило бы переименовать.

2024-06-22 16:16 UTC, lwof commented on main.py
> +    data_parser = get_data()
Точно не стоит это на / прикручивать. Сделай отдельную страничку плиз. С отдельным же шаблоном.

2024-06-23 14:59 UTC, Cosmmoss commented on get_data.py
> +        all_data = soup.find('div', class_='css-1nvf6xk eojktn00').find('div').findAll('a')
Я посмотрел и проверил на разных страницах Дрома - работает.

2024-06-23 17:33 UTC, Cosmmoss commented on get_data.py
> +def get_data():
Я сделал, чтобы функция принимала html как аргумент и теперь мне нужно импортировать две функции и вызывать две функции, а в видеолекциях Миша Корнеев наоборот старался при рефакторинге убрать функции и поменьше делать импорта функций.

2024-06-25 17:00 UTC, lwof approved these changes

2024-06-25 17:00 UTC, lwof commented on config.py
> +# DATASET_URL = 'https://auto.drom.ru/ford/mondeo/'
Удали закоментированные строки.

2024-06-25 17:02 UTC, lwof commented on get_data.py
> +def get_data():
Можно сделать третью функцию, которая будет вызывать эти две, и импортировать только третью :)

2024-06-28 18:48 UTC, lwof approved these changes

2024-06-28 18:50 UTC, merged