Сделал форму и страницу добавления задачи на парсинг
EliSoftCom/Final_project pull request #9
Opened 2024-06-29 19:53 UTC by Cosmmoss

2024-06-29 20:49 UTC, lwof requested changes
Основное что нужно пофиксить это упростить список зависимостей проекта. В нем должны быть только те пакеты которые прямо импортируются. Зависимости зависимостей мы перечислять не хотим, это ж не лок-файл.

2024-06-29 20:49 UTC, lwof commented on requirements.txt
> +blinker==1.8.2
Нет, так работать с зависимостями не надо. Оставь тут только то что является прямыми зависимостями (то что или из чего мы импортируем в проекте). И без версий, что бы ставились всегда последние версии. 

Что бы убедиться в том что все необходимые пакеты добавлены, нужно пересоздать виртуальное окружение, и удостовериться что сервис работает после установки requirements.txt.

2024-06-29 20:49 UTC, lwof commented on requirements.txt
> +colorama==0.4.6
Например это вообще не используется в проекте.

2024-06-29 20:49 UTC, lwof commented on requirements.txt
> +greenlet==3.0.3
Это вообще сложная штука, которую мы трогать вообще не хотим.

2024-06-29 20:49 UTC, lwof commented on webapp/__init__.py
> +        return render_template('index.html')
У меня есть стойкое ощущение, что тут были еще роуты. Вроде регистрации 🧐

2024-06-29 20:49 UTC, lwof commented on webapp/__init__.py
> +def create_app():
Так как ты перенес инициализацию приложение в инит, соответсвенно теперь по другому нужно запускать приложение. 

Добавь в ридми секцию с командами для запуска сервиса. (`flask run ...`)

2024-06-30 08:02 UTC, Cosmmoss commented on webapp/__init__.py
> +        return render_template('index.html')
Это может из предыдущего ПР, ветки - parser_Avito_#6_UP

2024-06-30 12:31 UTC, merged